### ISSUE TITLE
Figure out the data repo situation

### ISSUE THREAD

**Issue by jackiekazil** [18F/2015-foia#22]
We discussed this in passing, but we need to figure out the general setup of repo organization to make sure that the place where data is being referenced is consistent. 

Example where structure will start to matter:
https://github.com/18F/foia-hub/blob/cfb88236eb57984845dbdc6747287029f9397489/foia_hub/management/commands/load_agency_contacts.py#L5

This is a quick dev discussion.

**Comment by konklone** [comment]
The contacts data is so central that maybe we actually just make a repo just for it -- `foia-contacts` or the like -- and `foia-hub` can `git clone` it on demand.

**Comment by konklone** [comment]
Oops, sorry about that @mwlau, mis-clicked.

Just talked with @cmc333333 about this, and he's going to run with this. The notes I gave him to describe what I think is the best path forward:
- Basically keep the YAML format that we developed in https://github.com/18F/foia/tree/master/contacts
- Move them into a new repo in the `foia` organization, at https://github.com/foia/us-contacts
- Fix the bugs @jackiekazil identified in https://github.com/18F/foia-hub/issues/20, either through an adapted/rewritten scraper (as that ticket suggests) or through hand-editing if it's sufficient (since we're going to abandon the scraper afterwards anyway)
- Ensure the extra fields that the CSV offers (that are used by the current [DB loader](https://github.com/18F/foia-hub/blob/master/foia_hub/scripts/load_agency_contacts.py)) make it into the new YAML
- Ensure existing hand-edits to that YAML are preserved
- Mark the YAML scraper in `18f/foia` as deprecated, possibly archive it to some other branch.
- Update the [DB loader in `foia-hub`](https://github.com/18F/foia-hub/blob/master/foia_hub/scripts/load_agency_contacts.py) to simply download and load the new YAML data into the database
- Add a README, CONTRIBUTING.md, and LICENSE file to the new foia contacts repo based on [18F's open source policy](https://github.com/18F/open-source-policy)

**Comment by khandelwal** [comment]
This is resolved, but not completed. There's no work to be done.
